services:
  - type: web
    name: murf-voice-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: MURF_API_KEY
        sync: false
      - key: MURF_VOICE_ID
        value: en-US-natalie
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
